### PR TITLE
Sending you some new changes (9 files) - small edits, sorting lots of CSS/HTML, merge pull requests

### PR DESCRIPTION
**Pull request by compute-e**
I'm sending you some new changes - small edits to a few contributor pages, lots of sorting CSS today, many merge pull requests (which are copying over your edits).
Here's a description of today's work *(for things like CSS code and nav links colour)*:

> Checking all HTML files to sort out a few things with changed/moved CSS:
> • remove the old CSS code that's now part of a linked external stylesheet file for all pages
> • remove old background colours of active navigation links (see my comment) and add body tag styles
> • find any more files that use your old Github username so need to be updated (hyperlinks)
> • update a few old tags that I know aren't supported in HTML5 and fix small problems
> My comment: https://github.com/Magnogen/magnogen.github.io/pull/2#issuecomment-343754985

Unfortunately, I couldn't finish it because there's many HTML files to change  
so there's 9 left that need checking - found with the Github file finder.

### CODE REVIEW

**Review by compute-e — COMMENTED** [review]
Checked over what's changed in the diff. It looks alright.

**Comment by compute-e** [comment]
Here you go. I checked over the changes and you could too. Added a new label, [tidy-and-sort](https://github.com/Magnogen/magnogen.github.io/labels/tidy-and-sort).

**Comment by compute-e** [comment]
It appears you need to accept this pull request even though I'm a collaborator. However, you don't.

**Comment by Magnogen** [comment]
Thanks @user-e ! Your help is greatly appreciated.

**Comment by compute-e** [comment]
Great - it's nice to help and teamwork often makes jobs easier.  
By the way, I plan to add a small HTML5 game 🎮 _(that I created)_ from my webpages to this website soon, on the contributors list page as a fun example of what others have done.

**Comment by Magnogen** [comment]
Hi @user-e ! I've just fixed the nav-bar problem and started formatting it, will continue soon...

Feel free to add your game, and any other ideas you have too!

**Comment by user-e** [comment]
Hello there! I have a few ideas as well as the game and will continue to help, thanks.  
I don't think the nav-bar code and styles problem is fully sorted - there's some suggestions in my last  
comment at <https://github.com/user-e/magnogen.github.io-code-edits/pull/12#issuecomment-349348863>.

**Comment by compute-e** [comment]
Hello there @Magnogen ! I have a few ideas as well as the game and will continue to help,
thanks. There's a few more things to do for the nav-bar styles - a suggestion on my pull request
page at [user-e#13 (review)](https://github.com/user-e/magnogen.github.io-code-edits/pull/13#pullrequestreview-83977439) - we can continue this conversation there.

**Pull request merged**
