### PR TITLE
Update my contributor details page to add improvements

### PR DESCRIPTION
**Pull request by compute-e**
Hi Connor. I have one more contribution for your website, an improvement to my user details page.

I've spotted a weird issue that I can't solve on my user page. As this quote describes, the text on my page is appearing about twice as big as it should for an unknown reason. If you want, you could try to find the problem using Developer Tools in Google Chrome to look at how the elements are displayed.
> I tidied up the code to try to solve a problem with oversized text.
Using a comparison/diff between this file and hydronesium.html at http://www.quickdiff.com,
I looked for anything unusual that could be causing the text to appear twice as big as other user pages.

Thanks for helping out! ⭐

### CODE REVIEW

**Comment by compute-e** [comment]
I did a better comparison of the two webpage files without a diff tool and found something new in my  
contributor page: an un-closed `div` element that could be giving the following text its size.
After the tag was closed, the page looked very similar to the contributors list page but it was  
missing the document type tag, `<!DOCTYPE html>`. However, the page below with normal size has it  
so there's nothing new.

Nearly a week after, I found another piece of code with a mistake which didn't change anything  
when I fixed it in my next edit - a `</div>` closing tag without an element to end. Three months later,  
after looking at the code I think it's something about content in *h3* or *h4* tags (HTML [headings](https://www.w3schools.com/tags/tag_hn.asp)).

Some ideas to try for the problem:
- [x] Close the `div` element then check if that problem is happening - done.

- Maybe check the computed CSS values for `font-size` on the two pages using *Developer Tools*  
in a web browser (Google Chrome / Microsoft Edge) to see the size and where it comes from.  
Alternatively, there's a [JavaScript function](https://www.w3schools.com/jsref/jsref_getcomputedstyle.asp) to find out the values, that could  
be added to the pages with a few lines of code to show the results there.
For newer information, see <https://github.com/user-e/magnogen.github.io-code-edits/pull/12>.

**Comment by compute-e** [comment]
*@hydronesiumScratch  A question for you, unrelated to the website:*
Hmm... is ringing the school bells really possible using some .vbs code you've created...
well Microsoft Visual Basic Scripting is used by Windows system administrators (also in old malware) and can be executed with Internet Explorer (or by double clicking the file).
So perhaps it could be done by accessing the network servers (you can see many of these devices and some settings files from the Macs).
Wikipedia article where I found some info: <https://en.wikipedia.org/wiki/VBScript.>

**Comment by Magnogen** [comment]
Yes, it is actually possible as the school accounts are based on the servers. Then you can freely add a bit of extra code in order to run the code once the user logs off (people usually modify this bit of code in order to start it when the user logs on) and then you can execute the code for the bell-ringing-ness.

P.s. I didn't actually do this, it's just that I know how.

**Comment by compute-e** [comment]
You'll need to wait until next year for an April fool's trick/prank at school ;).
But really, it's a too noticeable prank that would cause trouble. Interesting though - I thought it was made up, a realistic lie.

**Comment by jimbob123x** [comment]
Hmmm... Curious. 
I think I need to see it to believe it.

**Comment by Magnogen** [comment]
Oh! So now you get involved jimbob123x!

**Comment by compute-e** [comment]
Thanks for inviting me to join your repository yesterday - _hydronesiumscratch.github.io_.  
I now have [push](https://help.github.com/articles/github-glossary/#push) access to the repository - so you don't need to confirm every change (commit) I make.  
If you want to understand something I do, there will be details in my commit description messages.  
rsz_screenshot_2017-10-06-13-52-21_kindlephoto-91478444

**Comment by compute-e** [comment]
@Magnogen When someone doesn't like the appearance of something, it's often easier to make it look different instead of destroying it and rebuilding all the parts. Deleting a user account instead of renaming it means data can get lost or needs to be transferred.  
Magnogen is shorter and different to hydronesium*Scratch*. It contains two real words:  
• "[magno](https://en.m.wiktionary.org/wiki/magno)", from Latin _magnus_, means great/mighty in Italian/Spanish.  
• "-[gen](https://www.google.co.uk/search?q=define+-gen)" is a word ending (suffix) that means a substance that produces something e.g. oxygen, genesis (origin/formation/creation), generation - *3rd gen*, general information *(British army)*.
Which meaning have you chosen? I was a bit curious.

Your username is used many times in 13 files that needed changing! Also, you've finally organized the large page design CSS code into a linked external stylesheet and added a webpage icon. I've renamed my repository now.
screenshot_2017-11-09-19-14-47_kindlephoto-33609442  
_There isn't an automatic redirect from the old Github Pages website._  
Also see https://user-e.github.io/magnogen.github.io-code-edits/, a Github Pages project site for my version of the website repository. The hyperlinks don't quite work because the links include the website as well as the full file path (they're absolute not relative) but it's still useful.

**Comment by Magnogen** [comment]
Interestingly, the username wasn't any of them. I made it using the following logic:

"Hydronesium" is a word created by mixing "Hydrogen" and "Magnesium".
"Magnogen" is the reversal: "Magnesium" and then "Hydrogen" afterwards.

The prefix word is "Magn-" (from _Magn_ esium) and "-ogen" (From Hydr _ogen_)

I can see why you were curious though.

**Comment by compute-e** [comment]
Great - so it continues to be about the elements Hydrogen and Magnesium.
By the way, you missed out some pages when changing the CSS code and your username - I've
noticed that the ones at <https://magnogen.github.io/hydredu/Bio/> haven't been updated.
Also, I think the newer background colour for active navigation links isn't as good -
compared to the previous light green `#4CAF50` hexadecimal colour code, the new `#0000FF` colour
is contrasting and there's too much blue. You could keep the old one (use a grey, green and white
colour scheme for your website) or switch to blue (and use [this colour picker](https://www.w3schools.com/colors/colors_picker.asp) to find a similar blue that works better).

- [x] Task: improve this newer background colour. Done - a better blue, `#0033cc`, has been chosen for the colour scheme.

Your older style | Here's the colour scheme I chose for my own webpages:
--- | ---
screenshot_2017-11-12-18-35-00_kindlephoto-97726184 | screenshot_2017-11-12-18-09-01_kindlephoto-96207312

P.S. Another important thing: without the slideshow on your homepage, that page looks a bit empty
(fixed this in new edits).

**Pull request merged**
