### PR TITLE
Update contributor page "EdJonez.html" - your 1st Pull Request

### PR DESCRIPTION
**Pull request by compute-e**
Hi there BPS Computing students (hydrolysis, nimble, FinIsHed - or without auto-correct: Connor, James, Tom). @hydronesiumScratch @jimbob123x
Here's an improved contributor details webpage from a programmer with knowledge about:

- HyperText Markup Language version 5 (HTML)
- Cascading Style Sheets (CSS)
- JavaScript (JS)
- Limited knowledge of server-side PHP

I have a few years of experience from creating my own private website.

### CODE REVIEW

**Review by Magnogen — APPROVED** [review]
Thanks Ed! Will add the commits to the web, thanks!

**Comment by compute-e** [comment]
```javascript
document.write("Thanks for helping. I also like how you've reused my username box code,"+
  "which might help you understand HTML/CSS better!");
```
A few mistakes I spotted in your newest 5 changed files (July 17th):
1. hydronesium.html - spelling mistake in Scratch profile URL
2. index.html - the `<center>` tag, unsupported in HTML5, is still used here
3. jimbob123x.html - "All about _hydronesium_" (you forgot to change the name)
4. user-e.html - [`&nbsp`](https://unicode-table.com/en/00A0/) needs to end in a semicolon (;) to make it the [Non-breaking space](https://en.m.wikipedia.org/wiki/Non-breaking_space#Encodings) _character entity reference_. This might be causing the extra large font sizes on that page.

**Comment by Magnogen** [comment]
Thanks! I will sort those out...

**Comment by Magnogen** [comment]
Sorted!

**Pull request merged**
